### PR TITLE
Grid layout & highlighted prayers

### PR DESCRIPTION
**Pull request by bradleyisfluent**

### CODE REVIEW

**Comment by nanorepublica** [comment]
Looks great! 

The width of the modal just needs to be wider for the longer prayer to not go off the top/bottom of the screen. Otherwise feel free to merge this!

**Comment by bradleyisfluent** [comment]
> Looks great!
> 
> The width of the modal just needs to be wider for the longer prayer to not go off the top/bottom of the screen. Otherwise feel free to merge this!

I've done this. The value is just set as a "wv" value in PrayerModal component. So feel free to tweak if you've seen it on screen.

I noticed in the docs a way to set the backdrop as blurred as well which really focuses the modal. See what you think, can be removed by getting rid of the "backdropFilter" property.

**Comment by nanorepublica** [comment]
adding the backdrop looks awesome, but seems to have slowed modal pop up considerably on my machine so perhaps drop that for now?

**Comment by bradleyisfluent** [comment]
> adding the backdrop looks awesome, but seems to have slowed modal pop up considerably on my machine so perhaps drop that for now?

Will do. Although could I just ask you check again as I've made some improvements to the loading of the styles this afternoon along with adding the masonary back. I don't think I had quite configured the binding of styles between client and server so it looks a bit smoother now and I'm hoping it will be a little faster all round.

**Pull request merged**
